name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: 
          - x86_64-unknown-linux-gnu

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Package
      shell: bash
      run: cd target/${{ matrix.target }}/release tar czvf ../../../<sfz>-${{ matrix.target }}.tar.gz <sfz> cd -
